CREATE TABLE Book (
  title VARCHAR(200) NOT NULL,
  author VARCHAR(100) NOT NULL,
  ISBN VARCHAR(40) NOT NULL,
  rented BOOLEAN NOT NULL,
  PRIMARY KEY (ISBN)
);

CREATE TABLE Reader(
  guid VARCHAR(50) NOT NULL,
  firstName VARCHAR(40) NOT NULL,
  lastName VARCHAR(60) NOT NULL,
  rents INTEGER NOT NULL,
  PRIMARY KEY (guid)
);

CREATE TABLE Rent(
  id INTEGER NOT NULL,
  bookISBN VARCHAR(40) NOT NULL,
  readerGuid VARCHAR(50) NOT NULL,
  startingDate DATE NOT NULL,
  closed BOOLEAN NOT NULL,
  PRIMARY KEY (id)
)