CREATE TABLE Book (
  title VARCHAR(200) NOT NULL,
  author VARCHAR(100) NOT NULL,
  id INT NOT NULL,
  rented BOOLEAN NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Reader(
  id INT NOT NULL,
  readerName VARCHAR(100) NOT NULL,
  rents INTEGER NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Rent(
  id INTEGER NOT NULL,
  bookId Int NOT NULL,
  readerId Int NOT NULL,
  startingDate DATE NOT NULL,
  closed BOOLEAN NOT NULL,
  PRIMARY KEY (id)
)